apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricewatcher
  labels:
    k8s-app: pricewatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: pricewatcher
  template:
    metadata:
      labels:
        k8s-app: pricewatcher
      name: pricewatcher
    spec:
      containers:
      - 
        name: pricewatcher
        image: pthomison/pricewatcher:{{ .Values.image.tag }}
        # args:
        # - --cert-dir=/tmp
        # - --secure-port=4443
        # - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        # - --kubelet-use-node-status-port
        # - --metric-resolution=15s
        

