apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricewatcher
  labels:
    k8s-app: pricewatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: pricewatcher
  template:
    metadata:
      labels:
        k8s-app: pricewatcher
      name: pricewatcher
    spec:
      containers:
      - 
        name: pricewatcher
        image: pthomison/pricewatcher:{{ .Values.image.tag }}
        args:
          - --dbfile=/data/pricewatcher.db
        volumeMounts:
        - name: shared-data
          mountPath: /data

      - 
        name: litestream
        image: litestream/litestream:0.3.9
        args:
          - replicate
          - /data/pricewatcher.db
          - s3://litestream-pricewatcher-backup
        volumeMounts:
        - name: shared-data
          mountPath: /data

  volumes:
  - name: shared-data
    emptyDir: {}