---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricewatcher-durable
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem