name: Build & Push Image

on:  
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Git Hash ENV
      run: echo "X_GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set Git Describe ENV
      run: echo "X_GIT_DESCRIBE=$(git describe --tags)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: pthomison
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{github.repository}}:${{env.X_GIT_DESCRIBE}},
          ${{github.repository}}:${{env.X_GIT_HASH}}